// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AppUser struct {
	ID       pgtype.UUID
	Username string
	Email    string
}

type Message struct {
	ID           pgtype.UUID
	CreatedAt    pgtype.Timestamp
	Text         string
	RoomID       pgtype.UUID
	SenderUserID pgtype.UUID
}

type Room struct {
	ID   pgtype.UUID
	Name string
}

type UserRoom struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
	RoomID pgtype.UUID
}
