// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"
)

type AppUser struct {
	ID       int64
	Username string
	Email    string
}

type Message struct {
	ID           int64
	CreatedAt    time.Time
	Text         string
	RoomID       int64
	SenderUserID int64
}

type Room struct {
	ID   int64
	Name string
}

type UserRoom struct {
	ID     int64
	UserID int64
	RoomID int64
}
